export const colorMapping: Record<string, string> = {
  a: "gray",
  b: "gold",
  c: "bronze",
  d: "brown",
  e: "yellow",
  f: "amber",
  g: "orange",
  h: "tomato",
  i: "red",
  j: "ruby",
  k: "crimson",
  l: "pink",
  m: "plum",
  n: "purple",
  o: "violet",
  p: "iris",
  q: "indigo",
  r: "blue",
  s: "cyan",
  t: "teal",
  u: "jade",
  v: "green",
  w: "grass",
  x: "lime",
  y: "mint",
  z: "sky",
};
